import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AR is COOL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Hello World!</h2>
  <div className="arjs-loader">
    <div>Loading, please wait...</div>
  </div>
  <body>
  {/* <!-- a-frame scene --> */}
  <a-scene
    vr-mode-ui="enabled: false;"
    renderer="logarithmicDepthBuffer: true;"
    embedded
    arjs="trackingMethod: best; sourceType: webcam;debugUIEnabled: false;"
  >
    {/* <!-- a-nft is the anchor that defines an Image Tracking entity --> */}
    {/* <!-- on 'url' use the path to the Image Descriptors created before. --> */}
    {/* <!-- the path should end with the name without the extension e.g. if file is 'pinball.fset' the path should end with 'pinball' --> */}
    {/* <a-nft
      type="nft"
      url="../"
      smooth="true"
      smoothCount="10"
      smoothTolerance=".01"
      smoothThreshold="5"
    >
      <a-entity
        gltf-model="<path-to-your-model>"
        scale="5 5 5"
        position="50 150 0"
      >
      </a-entity>
    </a-nft> */}
    {/* <!-- static camera that moves according to the device movemenents --> */}
    <a-entity camera></a-entity>
  </a-scene>
  </body>
      </main>
    </div>
  )
}
